// Generated by Physics Engine — @trubnikov/physics-engine
// Source: Physics Engine
// physics-engine export --format swiftui DESIGN.md

import SwiftUI

// MARK: - Colors (Energy Level System)
extension Color {
    /// Energy token: void
    static let void = Color(red: 0.020, green: 0.020, blue: 0.020)
    /// Energy token: void-text
    static let voidText = Color(red: 0.443, green: 0.443, blue: 0.478)
    /// Energy token: surface
    static let surface = Color(red: 0.067, green: 0.067, blue: 0.075)
    /// Energy token: surface-text
    static let surfaceText = Color(red: 0.894, green: 0.894, blue: 0.906)
    /// Energy token: interactive
    static let interactive = Color(red: 0.122, green: 0.122, blue: 0.141)
    /// Energy token: interactive-hover
    static let interactiveHover = Color(red: 0.165, green: 0.165, blue: 0.188)
    /// Energy token: interactive-text
    static let interactiveText = Color(red: 1.000, green: 1.000, blue: 1.000)
    /// Energy token: kinetic
    static let kinetic = Color(red: 0.231, green: 0.510, blue: 0.965)
    /// Energy token: kinetic-text
    static let kineticText = Color(red: 1.000, green: 1.000, blue: 1.000)
    /// Energy token: destructive
    static let destructive = Color(red: 0.937, green: 0.267, blue: 0.267)
    /// Energy token: destructive-text
    static let destructiveText = Color(red: 1.000, green: 1.000, blue: 1.000)
}

// MARK: - Spacing (Base Unit: 4px)
struct Spacing {
    /// 8px — Physics Engine spacing.compact
    static let compact: CGFloat = 8
    /// 16px — Physics Engine spacing.optimal
    static let optimal: CGFloat = 16
    /// 24px — Physics Engine spacing.loose
    static let loose: CGFloat = 24
    /// 48px — Physics Engine spacing.macro
    static let macro: CGFloat = 48
}

// MARK: - Radius (Topology Collapse)
struct Radius {
    /// Dynamic Radius: min(12, height / 2) — Topology Collapse formula
    static func dynamic(for height: CGFloat) -> CGFloat {
        min(12, height / 2)
    }
    /// 16px — Physics Engine rounded.surface
    static let surface: CGFloat = 16
}

// MARK: - Motion (Spring Kinematics)
struct Motion {
    /// Micro-interactions: buttons, toggles, chips
    static let micro = Animation.interpolatingSpring(
        mass: 0.5, stiffness: 500, damping: 25
    )
    /// Macro-topology: modals, sidebars, sheets
    static let macro = Animation.interpolatingSpring(
        mass: 1, stiffness: 250, damping: 30
    )
    /// Press compression — Kinematic state law
    static let tapScale: CGFloat = 0.96
}

// MARK: - Accessibility (Fitts Law)
struct Accessibility {
    /// Fitts Law minimum touch target (44×44pt)
    static let minTapTarget: CGFloat = 44
    /// Focus ring: 2pt kinetic-colored ring, 2pt offset
    static let focusRingWidth: CGFloat = 2
    static let focusRingOffset: CGFloat = 2
    static let focusRingColor = Color.kinetic
}

// MARK: - Typography (1.25 Major Third Scale)
extension Font {
    /// body — 1rem, weight 400
    static let body = Font.system(size: 16, weight: .light)
    /// h3 — 1.25rem, weight 500
    static let h3 = Font.system(size: 16, weight: .medium)
    /// h2 — 1.5625rem, weight 600
    static let h2 = Font.system(size: 16, weight: .semibold)
    /// h1 — 1.953rem, weight 700
    static let h1 = Font.system(size: 16, weight: .bold)
}
