/** Tailwind config generated from Physics Engine DESIGN.md — Calm Focus */
/** Generated by: physics-engine export --format tailwind DESIGN.md */

/** @type {import("tailwindcss").Config} */
export default {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
              "void": "#050505",
              "surface": "#111113",
              "interactive": "#1F1F24",
              "interactive-hover": "#2A2A30",
              "kinetic": "#3B82F6",
              "kinetic-glow": "rgba(59, 130, 246, 0.25)",
              "kinetic-text": "#FFFFFF",
              "destructive": "#EF4444",
              "muted": "#71717A",
              "surface-text": "#E4E4E7",
              "void-text": "#71717A",
              "note-yellow": "#854D0E",
              "note-yellow-surface": "rgba(234, 179, 8, 0.08)",
              "note-green": "#166534",
              "note-green-surface": "rgba(34, 197, 94, 0.08)",
              "note-purple": "#6B21A8",
              "note-purple-surface": "rgba(168, 85, 247, 0.08)",
              "divider": "rgba(255, 255, 255, 0.06)",
              "selection": "rgba(59, 130, 246, 0.15)"
      },
      spacing: {
              "compact": "8px",
              "optimal": "16px",
              "loose": "24px",
              "macro": "48px",
              "prose": "40px"
      },
      borderRadius: {
              "surface": "16px",
              "tag": "6px"
      },
      fontSize: {
              "display": "31px",
              "section": "25px",
              "component": "20px",
              "body": "16px",
              "label": "13px",
              "prose": "18px",
              "note-title": "25px"
      },
      lineHeight: {
              "display": "34px",
              "section": "30px",
              "component": "28px",
              "body": "26px",
              "label": "20px",
              "prose": "32px",
              "note-title": "32px"
      },
    },
  },
  plugins: [],
};