/** Tailwind config generated from Physics Engine DESIGN.md — Dark Command */
/** Generated by: physics-engine export --format tailwind DESIGN.md */

/** @type {import("tailwindcss").Config} */
export default {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
              "void": "#050505",
              "surface": "#111113",
              "interactive": "#1F1F24",
              "interactive-hover": "#2A2A30",
              "kinetic": "#3B82F6",
              "kinetic-glow": "rgba(59, 130, 246, 0.25)",
              "kinetic-text": "#FFFFFF",
              "destructive": "#EF4444",
              "destructive-glow": "rgba(239, 68, 68, 0.25)",
              "muted": "#71717A",
              "surface-text": "#E4E4E7",
              "void-text": "#71717A",
              "success": "#22C55E",
              "warning": "#F59E0B",
              "code-surface": "#0D0D0F",
              "code-string": "#86EFAC",
              "code-keyword": "#93C5FD",
              "code-comment": "#52525B"
      },
      spacing: {
              "compact": "8px",
              "optimal": "16px",
              "loose": "24px",
              "macro": "48px"
      },
      borderRadius: {
              "surface": "16px",
              "code": "8px"
      },
      fontSize: {
              "display": "31px",
              "section": "25px",
              "component": "20px",
              "body": "16px",
              "label": "13px",
              "code": "14px"
      },
      lineHeight: {
              "display": "34px",
              "section": "30px",
              "component": "28px",
              "body": "26px",
              "label": "20px",
              "code": "22px"
      },
    },
  },
  plugins: [],
};