/**
 * Physics Engine Exporter
 * Converts DESIGN.md tokens to Tailwind config, W3C DTCG format, and SwiftUI.
 */

import { parseDesignMd, resolveRef, DesignSystem } from './parse.js';

export type ExportFormat = 'tailwind' | 'dtcg' | 'swiftui';

// ─── Tailwind Export ──────────────────────────────────────────────────────────

function toTailwind(ds: DesignSystem): Record<string, any> {
  const colors: Record<string, string> = {};
  for (const [key, value] of Object.entries(ds.colors || {})) {
    const camel = key.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
    colors[camel] = value;
  }

  const spacing: Record<string, string> = {};
  for (const [key, value] of Object.entries(ds.spacing || {})) {
    spacing[key] = value;
  }

  const borderRadius: Record<string, string> = {};
  for (const [key, value] of Object.entries(ds.rounded || {})) {
    borderRadius[key] = value;
  }

  const fontSize: Record<string, [string, Record<string, string | number>]> = {};
  for (const [key, token] of Object.entries(ds.typography || {})) {
    fontSize[key] = [
      token.fontSize ?? '1rem',
      {
        lineHeight: String(token.lineHeight ?? 1.5),
        fontWeight: String(token.fontWeight ?? 400),
        letterSpacing: token.letterSpacing ?? 'normal',
      },
    ];
  }

  return {
    theme: {
      extend: {
        colors,
        spacing,
        borderRadius,
        fontSize,
      },
    },
  };
}

// ─── DTCG Export ──────────────────────────────────────────────────────────────

function dtcgToken(value: string, type: string, description?: string) {
  const token: Record<string, any> = { $value: value, $type: type };
  if (description) token.$description = description;
  return token;
}

function toDtcg(ds: DesignSystem): Record<string, any> {
  const output: Record<string, any> = {};

  output.colors = {};
  for (const [key, value] of Object.entries(ds.colors || {})) {
    output.colors[key] = dtcgToken(value, 'color');
  }

  output.typography = {};
  for (const [key, token] of Object.entries(ds.typography || {})) {
    output.typography[key] = {
      $type: 'typography',
      $value: {
        fontFamily: token.fontFamily,
        fontSize: token.fontSize,
        fontWeight: token.fontWeight,
        lineHeight: token.lineHeight,
        letterSpacing: token.letterSpacing,
      },
    };
  }

  output.spacing = {};
  for (const [key, value] of Object.entries(ds.spacing || {})) {
    output.spacing[key] = dtcgToken(value, 'dimension');
  }

  output.borderRadius = {};
  for (const [key, value] of Object.entries(ds.rounded || {})) {
    output.borderRadius[key] = dtcgToken(value, 'dimension');
  }

  output.components = {};
  for (const [compName, comp] of Object.entries(ds.components || {})) {
    const resolved: Record<string, string> = {};
    for (const [prop, value] of Object.entries(comp)) {
      if (typeof value === 'string') {
        resolved[prop] = resolveRef(value, ds) ?? value;
      }
    }
    output.components[compName] = { $type: 'composite', $value: resolved };
  }

  return output;
}

// ─── SwiftUI Export ───────────────────────────────────────────────────────────

function hexToSwiftUIColor(hex: string): string {
  const clean = hex.replace('#', '');
  if (clean.length !== 6) return '// invalid hex';
  const r = (parseInt(clean.slice(0, 2), 16) / 255).toFixed(3);
  const g = (parseInt(clean.slice(2, 4), 16) / 255).toFixed(3);
  const b = (parseInt(clean.slice(4, 6), 16) / 255).toFixed(3);
  return `Color(red: ${r}, green: ${g}, blue: ${b})`;
}

function parsePxValue(val: string): number | null {
  const m = val.match(/^(\d+(?:\.\d+)?)px$/);
  return m ? parseFloat(m[1]) : null;
}

function toSwiftIdentifier(kebab: string): string {
  return kebab.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

function toSwiftUI(ds: DesignSystem): string {
  const name = ds.name ?? 'DesignSystem';
  const lines: string[] = [];

  lines.push(`// Generated by Physics Engine — @trubnikov/physics-engine`);
  lines.push(`// Source: ${name}`);
  lines.push(`// physics-engine export --format swiftui DESIGN.md`);
  lines.push('');
  lines.push('import SwiftUI');
  lines.push('');

  // ── Colors ──
  lines.push('// MARK: - Colors (Energy Level System)');
  lines.push('extension Color {');
  for (const [key, value] of Object.entries(ds.colors || {})) {
    if (typeof value !== 'string' || !value.startsWith('#')) continue;
    const id = toSwiftIdentifier(key);
    lines.push(`    /// Energy token: ${key}`);
    lines.push(`    static let ${id} = ${hexToSwiftUIColor(value)}`);
  }
  lines.push('}');
  lines.push('');

  // ── Spacing ──
  lines.push('// MARK: - Spacing (Base Unit: 4px)');
  lines.push('struct Spacing {');
  for (const [key, value] of Object.entries(ds.spacing || {})) {
    const px = parsePxValue(String(value));
    if (px === null) continue;
    lines.push(`    /// ${value} — Physics Engine spacing.${key}`);
    lines.push(`    static let ${key}: CGFloat = ${px}`);
  }
  lines.push('}');
  lines.push('');

  // ── Border Radius ──
  lines.push('// MARK: - Radius (Topology Collapse)');
  lines.push('struct Radius {');
  lines.push('    /// Dynamic Radius: min(12, height / 2) — Topology Collapse formula');
  lines.push('    static func dynamic(for height: CGFloat) -> CGFloat {');
  lines.push('        min(12, height / 2)');
  lines.push('    }');
  for (const [key, value] of Object.entries(ds.rounded || {})) {
    if (String(value).startsWith('min(')) continue; // handled above
    const px = parsePxValue(String(value));
    if (px === null) continue;
    lines.push(`    /// ${value} — Physics Engine rounded.${key}`);
    lines.push(`    static let ${key}: CGFloat = ${px}`);
  }
  lines.push('}');
  lines.push('');

  // ── Motion (Spring Presets) ──
  const motion = (ds as any).motion;
  if (motion) {
    lines.push('// MARK: - Motion (Spring Kinematics)');
    lines.push('struct Motion {');
    if (motion.micro) {
      const m = motion.micro;
      lines.push('    /// Micro-interactions: buttons, toggles, chips');
      lines.push(`    static let micro = Animation.interpolatingSpring(`);
      lines.push(`        mass: ${m.mass}, stiffness: ${m.stiffness}, damping: ${m.damping}`);
      lines.push(`    )`);
    }
    if (motion.macro) {
      const m = motion.macro;
      lines.push('    /// Macro-topology: modals, sidebars, sheets');
      lines.push(`    static let macro = Animation.interpolatingSpring(`);
      lines.push(`        mass: ${m.mass}, stiffness: ${m.stiffness}, damping: ${m.damping}`);
      lines.push(`    )`);
    }
    const tapScale = motion['tap-scale'];
    if (tapScale) {
      lines.push(`    /// Press compression — Kinematic state law`);
      lines.push(`    static let tapScale: CGFloat = ${tapScale}`);
    }
    lines.push('}');
    lines.push('');
  }

  // ── Accessibility ──
  lines.push('// MARK: - Accessibility (Fitts Law)');
  lines.push('struct Accessibility {');
  lines.push('    /// Fitts Law minimum touch target (44×44pt)');
  lines.push('    static let minTapTarget: CGFloat = 44');
  lines.push('    /// Focus ring: 2pt kinetic-colored ring, 2pt offset');
  lines.push('    static let focusRingWidth: CGFloat = 2');
  lines.push('    static let focusRingOffset: CGFloat = 2');
  lines.push('    static let focusRingColor = Color.kinetic');
  lines.push('}');
  lines.push('');

  // ── Typography ──
  const typography = ds.typography || {};
  if (Object.keys(typography).length > 0) {
    lines.push('// MARK: - Typography (1.25 Major Third Scale)');
    lines.push('extension Font {');
    for (const [key, token] of Object.entries(typography)) {
      const size = parsePxValue(String(token.fontSize ?? '16px')) ?? 16;
      const weight = swiftFontWeight(token.fontWeight ?? 400);
      lines.push(`    /// ${key} — ${token.fontSize}, weight ${token.fontWeight}`);
      lines.push(`    static let ${toSwiftIdentifier(key)} = Font.system(size: ${size}, weight: ${weight})`);
    }
    lines.push('}');
  }

  return lines.join('\n');
}

function swiftFontWeight(weight: number | string): string {
  const w = Number(weight);
  if (w >= 700) return '.bold';
  if (w >= 600) return '.semibold';
  if (w >= 500) return '.medium';
  if (w >= 300) return '.light';
  return '.regular';
}

// ─── Main Export Function ─────────────────────────────────────────────────────

export function exportTokens(content: string, format: ExportFormat): string {
  const { frontMatter, error } = parseDesignMd(content);

  if (error || !frontMatter) {
    throw new Error(error ?? 'Failed to parse DESIGN.md');
  }

  if (format === 'tailwind') {
    return JSON.stringify(toTailwind(frontMatter), null, 2);
  }

  if (format === 'dtcg') {
    return JSON.stringify(toDtcg(frontMatter), null, 2);
  }

  if (format === 'swiftui') {
    return toSwiftUI(frontMatter);
  }

  throw new Error(`Unknown format: ${format}. Use "tailwind", "dtcg", or "swiftui".`);
}
